version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: jamming_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jamming_studio
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ../schema:/docker-entrypoint-initdb.d

volumes:
  db_data: